# Generated by Django 4.2.4 on 2023-08-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralview',
            name='viewer',
        ),
    ]
