# Generated by Django 4.2.4 on 2023-08-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_level_customuser_level'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
    ]
