# Generated by Django 4.2.4 on 2023-08-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_points_eared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='points_eared',
            new_name='points_earned',
        ),
    ]
